### ISSUE TITLE
failed build cyclonedds-cxx-0.8.0beta1

### ISSUE THREAD

**Issue by BobDLA** [eclipse-cyclonedds/cyclonedds-cxx#138]
got a error 
cyclonedds-cxx-0.8.0beta1/src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp:163:10: error: ‘dds_is_loan_available’ was not declared in this scope
   return dds_is_loan_available(writer);
          ^~~~~~~~~~~~~~~~~~~~~
/home/xiaoran/work/cyclonedds-cxx-0.8.0beta1/src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp:163:10: note: suggested alternative: ‘is_loan_available’
   return dds_is_loan_available(writer);
          ^~~~~~~~~~~~~~~~~~~~~
          is_loan_available

**Comment by eboasson** [comment]
The commit that introduces `dds_is_loan_available` is 69375ca6088e75ac2a479a8e86d86564e57643a7 from 30 June, probably the easiest is to use `cyclonedds`'s releases/0.8.0 branch instead.

If for some reason it is impractical for you to update the core library, then the compiler's suggested alternative works, too.

**Comment by k0ekk0ek** [comment]
Hi @BobDLA! I've just released/branched 0.8. cyclonedds-cxx 0.8 should build on cyclonedds 0.8 and cyclonedds-cxx's development branch should be fully compatible with cyclonedds's. Closing this ticket. Feel free to reopen or ask further questions if something doesn't work for you. Thanks for reporting!
